version: '3.8'

services:
  cashback-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashback-app
    restart: unless-stopped
    networks:
      - caddy
      - cashback-network
    environment:
      - DATABASE_URL=postgresql://cashback_user:cashback_pass@host.docker.internal:5432/cashback_db
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=https://cashback.doroninva.ru
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "caddy=cashback.doroninva.ru"
      - "caddy.reverse_proxy={{upstreams 3000}}"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  caddy:
    external: true
    name: caddy
  cashback-network:
    driver: bridge
